title:            Martin's Note
description:      
url:              http://ies.pw
baseurl:          
signoff:          Martin Xu
disqus_shortname: martin-note
google_analytics_id: UA-11897577-2

links:
  - name:         Home
    url:          /
    
  # - name:         About
    # url:          /about
  - name:         Email
    url:          mailto:martin.xus@gmail.com
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
